### ISSUE TITLE
Path wildcard can be mistaken for long comment delimiter

### ISSUE THREAD

**Issue by cumber** [motus/pig.vim#10]
My organisation has a bunch of pig scripts that begin with something like:

    REGISTER /path/to/some/libs/*.jar

Unfortunately the syntax highlighting here picks up the `/*` as the beginning of a comment, and treats the entire rest of the file as a comment.

**Comment by motus** [comment]
Thanks for pointing it out! I will try to fix the issue ASAP.

**Comment by motus** [comment]
@cumber could you please check out the latest master and check if the fix works for you?

If it does, please go ahead and close the issue. Thank you!

**Comment by cumber** [comment]
Thanks for the quick fix! The new version works fine.
